# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8c90ec3458bc58800f5d77208c29b56dfe0d407695ae39aa08f472a1dc9707e5bd34dc99b3cea250ca49a621001c97dcdc45f44a397c5601e94ab026f5f4cd9

test:
  secret_key_base: 86dc3a1af45d069791ad691a787f68fe77f0d20f2d05e826bf1cca2a4979f50df0a88409e7d7e6b814a45f74bdfdae94850850e6198b6051e644aa77899e146c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
