# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e575dda0c7ff9a3b9f578855d795ca5b1a956280bb50a856d42711bae9f68ec4a3d49fb18120c42c3841f653b0e24da125c8f34c0256f9ae0a1ca4089c7200

test:
  secret_key_base: 485514332ea6d79dbdd4e9e48816124a94667221bd40e4d18f2ca951c43447b3b02acac0185bb9a18f635e84e92fe84eb6da7ea659e70b129670aaa8441e660e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
